services:
  # spin up a database
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: etltask
      POSTGRES_PASSWORD: etltask
      POSTGRES_DB: etltask-test-db
    ports:
      - '5432:5432'
    volumes:
      - etltask-test-db:/var/lib/postgresql/data

volumes:
  etltask-test-db: {}
